export const profile = {
  name: "Hojin Han",
  koreanName: "한호진",
  birthYear: "20XX",
  role: "Security Researcher",
  location: "Republic of Korea",
  portrait: "/profile.webp",
  portraitAlt: "Hojin Han standing by the Han River at night",
  email: "seupjak@korea.ac.kr",
  github: "",
  blog: "https://blog.naver.com/seupjak_",
  scholar: "",
  linkedin: "",
  cv: "",
};
