export const profile = {
  name: "Hojin Han",
  koreanName: "한호진",
  birthYear: "20XX",
  role: "Security Researcher",
  location: "Republic of Korea",
  portrait: "/profile.webp",
  portraitAlt: "Hojin Han standing by the Han River at night",
  email: "seupjak@korea.ac.kr",
  github: "https://github.com/hanhojinx",
  instagram: "https://instagram.com/hxnhojin",
  discord: "https://discord.com/users/487278496390053889",
  blog: "https://blog.naver.com/seupjak_",
  scholar: "",
  linkedin: "",
  cv: "",
};
